USE master

GO

CREATE DATABASE OLS ON
	(
		NAME='OLS_Data',
		FILENAME='D:\SQL Server 2008 Data\OLS.mdf',
		SIZE=3,
		MAXSIZE=UNLIMITED,
		FILEGROWTH=200MB
	) LOG ON
	(
		NAME='OLS_Log',
		FILENAME='D:\SQL Server 2008 Data\OLS_log.ldf',
		SIZE=1,
		MAXSIZE=UNLIMITED,
		FILEGROWTH=200MB
	)

GO